export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_START = "REGISTER_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GETAUTH_USER_START = "GETAUTH_USER_START";
export const GETAUTH_USER_SUCCESS = "GETAUTH_USER_SUCCESS";
export const GETAUTH_USER_FAIL = "GETAUTH_USER_FAIL";

export const GETPOSTS_START = "GETPOSTS_START";
export const GETPOSTS_SUCCESS = "GETPOSTS_SUCCESS";
export const GETPOSTS_FAIL = "GETPOSTS_FAIL";

export const GET_POST_START = "GET_POST_START";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAIL = "GET_POST_FAIL";

export const LIKE_POST_START = "LIKE_POST_START";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL";

export const UNLIKE_POST_START = "UNLIKE_POST_START";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";
export const UNLIKE_POST_FAIL = "UNLIKE_POST_FAIL";

export const MAKE_COMMENT_START = "MAKE_COMMENT_START";
export const MAKE_COMMENT_SUCCESS = "MAKE_COMMENT_SUCCESS";

export const LOGOUT = "LOGOUT";